Params classes
T4MVC/R4MVC pull request #139
Opened 2019-11-15 08:20 UTC by duncansmart

For access to Controller Action/Page Handler parameter names

2020-04-05 10:48 UTC, MarkFl12 commented
I find myself in need of this feature, is there anything I can do to help get this merged and released?

2020-04-27 14:35 UTC, btihanyi requested changes
Nice work, I also need this feature for upgrading to ASP.NET Core.

2020-04-27 14:35 UTC, btihanyi commented on src/R4Mvc.Tools/Services/ControllerGeneratorService.cs
> +            var methods = SyntaxNodeHelpers.GetPublicNonGeneratedControllerMethods(controller.Symbol);
I would add a `.ToList()` call for performance reasons.

2020-04-27 14:35 UTC, btihanyi commented on src/R4Mvc.Tools/Services/ControllerGeneratorService.cs
> +                    .WithStaticFieldBackedProperty($"{m.Name}Params", $"ActionParamsClass_{m.Name}", SyntaxKind.PublicKeyword)
The 'Params' suffix should come from the settings json file with the name of 'ParamsPropertySuffix'.

2020-04-27 14:35 UTC, btihanyi commented on src/R4Mvc.Tools/Services/ControllerGeneratorService.cs
> +                .ForEach(methods.Where(m => m.Parameters.Any()), (c, m) => c
Parameter generation should be optional (as in the original T4MVC), which would be decided from the settings json file with the name 'GenerateParamsForActionMethods'.

2021-07-11 19:43 UTC, artiomchi commented
Hey all,
Thanks a lot for your contribution @duncansmart, and the review on this @btihanyi 
I've applied the comments and am merging this PR now.

Since #148 was recently merged, I'm applying those changes too, so if the param name was renamed, the params class will have the updated value (but the name will match the param name in code)

2021-07-11 19:43 UTC, merged